# Automatically approve PRs made by Dependabot

name: Auto Approve Dependabot PR's

on:
  pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
        run: echo ${{github.actor}}
